spring:
  #  默认profile是default
  profiles:
    active: dev,test,production
  #  增加banner
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  messages:
    basename: i18n/messages
    encoding: UTF-8